spring.docker.compose.enabled=false
spring.data.redis.host=${redis.host}
spring.data.redis.port=${redis.port}

# Migration {Liquibase}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.liquibase.drop-first=false

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Use if problem to read/write to db, logging liquibase
#logging.level.liquibase=DEBUG
#logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

# AI for analytics {Ollama}
spring.ai.ollama.base-url=${ollama.url}
spring.ai.ollama.chat.model=${ollama.model}

# Broker of messages {Rabbit MQ}
spring.rabbitmq.host=${rebbitmq.host}
spring.rabbitmq.port=${rebbitmq.port}
spring.rabbitmq.username=${rebbitmq.username}
spring.rabbitmq.password=${rebbitmq.password}