CREATE TABLE mood_history
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      DECIMAL,
    mood         VARCHAR(255),
    triggered_at BIGINT,
    CONSTRAINT pk_mood_history PRIMARY KEY (id)
);

ALTER TABLE mood_history
    ADD CONSTRAINT FK_MOOD_HISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES "main_user" (id);