CREATE TABLE risk_flag
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    flag         JSONB,
    triggered_at BIGINT,
    CONSTRAINT pk_risk_flag PRIMARY KEY (id)
);

ALTER TABLE risk_flag
    ADD CONSTRAINT FK_RISK_FLAG_ON_USER FOREIGN KEY (user_id) REFERENCES "main_user" (id);