CREATE TABLE session_message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id UUID,
    role       VARCHAR(255),
    content    VARCHAR(255),
    created_at BIGINT,
    CONSTRAINT pk_session_message PRIMARY KEY (id)
);

ALTER TABLE session_message
    ADD CONSTRAINT FK_SESSION_MESSAGE_ON_SESSION FOREIGN KEY (session_id) REFERENCES "session" (id);